blank_issues_enabled: true
contact_links:
  - name: Question & Support
    url: https://forum.nette.org/en/f47-latte
    about: If you have a question or are looking for advice, please post on our discussions forum.
  - name: â— PhpStorm Latte plugin issues report here â—
    url: https://github.com/nette-intellij/intellij-latte/issues
    about: Thanks ğŸ™
